---
- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t awsgroup5team . 
    args:
     chdir: /opt/docker/aws-code

  - name: create tag to push image onto dockerhub
    command: docker tag awsgroup5team:latest public.ecr.aws/k0n3h6e5/awsgroup5team:latest

  - name: push docker image
    command: docker push public.ecr.aws/k0n3h6e5/awsgroup5team:latest
